#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

echo 'Set permissions for persisted data...'
mkdir -p '/srv/wordpress/html'
chown "1000:1000" '/srv/wordpress/html'
chmod 777 '/srv/wordpress/html'
