os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - export src_dir=$(pwd)
  - export dir="${src_dir}/images/${VERSION}/php${PHP_VERSION}-${VARIANT}"
  - export DOCKER_REPO=monogramm/docker-wordpress
  - export DOCKERFILE_PATH=Dockerfile
  - export DOCKER_TAG=$VERSION-$VARIANT-travis
  - export IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}

install:
  - cd "$dir"
  # Build project
  - ./hooks/run build

before_script:
  - docker images

script:
  - cd "$dir"
  # Execute project CI Tests
  - ./hooks/run test

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache

env: # Environments
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=apache
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=apache
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=apache
    - VERSION=5.7 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.7 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.7 PHP_VERSION=7.4 VARIANT=apache
