os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - export src_dir=$(pwd)
  - export dir="${src_dir}/images/${VERSION}/php${PHP_VERSION}-${VARIANT}"
  - export DOCKER_REPO=monogramm/docker-wordpress
  - export DOCKERFILE_PATH=Dockerfile
  - export DOCKER_TAG=$VERSION-$VARIANT-travis
  - export IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}

install:
  - cd "$dir"
  # Test container build
  - docker build --build-arg "TAG=${DOCKER_TAG}" --build-arg "VCS_REF=$(git rev-parse --short HEAD)" --build-arg "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
  #- docker-compose build

before_script:
  - docker images

script:
  - cd "$dir"
  # Test container run (docker)
  #- docker run --name "app" -d "$IMAGE_NAME"
  #- docker ps
  #- docker logs "app"
  #- docker stop "app"
  #- docker rm -f -v "app"
  # Test container run (docker-compose)
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up" || exit 1
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up" || exit 1
  - echo 'Wait until sites and apps database installed (4-5 minutes)' && sleep 300
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up"
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up"
  # Test container restart
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up"
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache

env: # Environments
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.4 PHP_VERSION=7.4 VARIANT=apache
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.5 PHP_VERSION=7.4 VARIANT=apache
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=fpm-alpine
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=fpm
    - VERSION=5.6 PHP_VERSION=7.4 VARIANT=apache
