os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - name="wordpress"
  - image="monogramm/docker-wordpress:${VERSION}${PHP_VERSION:+-$PHP_VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}/php${PHP_VERSION}-${VARIANT}"

script:
  - travis_retry docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --name "$name" -d "$image" "$dir"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache

env: # Environments
    - VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.1 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.1 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.2 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.2 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.3 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.3 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.3 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.3 PHP_VERSION=7.2 VARIANT=apache
