os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master
    - develop

before_install:
  - env | sort
  - export name="wordpress"
  - export image="monogramm/docker-wordpress:${VERSION}${PHP_VERSION:+-$PHP_VERSION}${VARIANT:+-$VARIANT}"
  - export home=$(pwd)
  - export dir="${home}/images/${VERSION}/php${PHP_VERSION}-${VARIANT}"

install:
  # Test container build
  - travis_retry docker build -t "$image" "$dir"

before_script:
  - docker images

script:
  # Test container run (docker)
  - docker run --name "$name" -d "$image" "$dir"
  - docker ps
  - docker logs "$name"
  - docker stop "$name"
  - docker rm -f -v "$name"
  # Test container run (docker-compose)
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up" || exit 1
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up" || exit 1
  - echo 'Wait until sites and apps database installed (4-5 minutes)' && sleep 300
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up"
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up"
  # Test container restart
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 20
  - docker-compose ps
  - docker-compose logs "wordpressdb"
  - docker-compose ps "wordpressdb" | grep "Up"
  - docker-compose logs "wordpress"
  - docker-compose ps "wordpress" | grep "Up"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=4.9 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - env: VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache

env: # Environments
    - VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm-alpine
    - VERSION=5.0 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.0 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.0 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=5.0 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.0 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm-alpine
    - VERSION=5.1 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.1 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.1 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=5.1 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.1 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm-alpine
    - VERSION=5.2 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.2 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.2 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=5.2 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.2 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.3 PHP_VERSION=7.3 VARIANT=fpm-alpine
    - VERSION=5.3 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.3 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.3 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=5.3 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.3 PHP_VERSION=7.2 VARIANT=apache
    - VERSION=5.4 PHP_VERSION=7.3 VARIANT=fpm-alpine
    - VERSION=5.4 PHP_VERSION=7.3 VARIANT=fpm
    - VERSION=5.4 PHP_VERSION=7.3 VARIANT=apache
    - VERSION=5.4 PHP_VERSION=7.2 VARIANT=fpm-alpine
    - VERSION=5.4 PHP_VERSION=7.2 VARIANT=fpm
    - VERSION=5.4 PHP_VERSION=7.2 VARIANT=apache
