version: "2.3"

volumes:
  db:
  data:

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    depends_on:
      - wordpress
    environment:
      - DOCKER_TEST_CONTAINER=wordpress
      # FIXME no answer from curl
      #- DOCKER_WEB_CONTAINER=wordpressnginx
    volumes_from:
      - wordpress
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  wordpress:
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH}
      args:
        - TAG=${DOCKER_TAG}
    image: ${IMAGE_NAME}
    container_name: wordpress
    #restart: always
    depends_on:
      wordpressdb:
        condition: service_healthy
    links:
      - wordpressdb
    expose:
      - "9000"
    #ports:
    #  - "9090:9000"
    # To persist WP locally
    volumes:
      - data:/var/www/html
      #- /srv/wordpress/html:/var/www/html
    environment:
      # Site Config
      - WORDPRESS_USERNAME=${WORDPRESS_ADMIN_LOGIN}
      - WORDPRESS_PASSWORD=${WORDPRESS_ADMIN_PWD}
      - WORDPRESS_EMAIL=admin@${DOMAIN}
      - WORDPRESS_FIRST_NAME=Admin
      - WORDPRESS_LAST_NAME=WordPress
      - WORDPRESS_BLOG_NAME=${WORDPRESS_BLOG_NAME}
      # DB Config
      - WORDPRESS_DB_HOST=wordpressdb:3306
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PWD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TBL_PREFIX}
      # SMTP Config
      - SMTP_HOST=wordpressmailer
      - SMTP_PORT=1025
      - SMTP_DOMAIN=${DOMAIN}
      - SMTP_USER=${WORDPRESS_SMTP_USER}
      - SMTP_PASSWORD=${WORDPRESS_SMTP_PWD}
      - SMTP_PROTOCOL=

  wordpressdb:
    image: mariadb:latest
    container_name: wordpressdb
    #restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--password=${WORDPRESS_DB_ROOT_PWD}",
        ]
      timeout: 10s
      retries: 5
    expose:
      - "3306"
    #ports:
    #  - "33306:3306"
    volumes:
      - db:/var/lib/mysql
      #- /srv/wordpress/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_ROOT_PWD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PWD}

  wordpressnginx:
    image: nginx:latest
    container_name: wordpressnginx
    restart: always
    expose:
      - "80"
    #ports:
    #  - "8080:80"
    #  # If you need SSL connection
    #  # - "8443:443"
    depends_on:
      - wordpress
    links:
      - wordpress
    volumes:
      - data:/var/www/html
      #- /srv/wordpress/html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      - NGINX_PHP_CGI=wordpress:9000 # same as wordpress container name

  wordpressmailer:
    image: sj26/mailcatcher:latest
    hostname: wordpressmailer
    container_name: wordpressmailer
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

